---
title: "SOL speed accuracy munging"
author: "Kyle MacDonald"
date: "October 1, 2015"
output: html_document
---

## Script to munge sol eye movement data

```{r}
rm(list=ls())
```

```{r}
source("../../analysis/helpers/libraries_v_3.6.R")
library(dplyr)
library(stringr)
```

### Read in icharts for V1 and Trio

```{r}
v1_df <- read.csv("../../processed_data/vanilla/sol-ichart-merged-post-gating.csv", stringsAsFactors = F)
trio_df <- read.csv("TrioFace26n24orig_km.csv", stringsAsFactors = F)
trio_prescreening <- read.csv("trio_prescreening_info.csv", sep = ",", stringsAsFactors = F)
```

Add trio prescreening info to iChart.

```{r}
trio_prescreening %<>%
    select(Sub.Num, PSO.Reason, Tr.Num) %>% 
    mutate(Sub.Num = as.character(Sub.Num),
           Tr.Num = as.character(Tr.Num))

trio_df <- left_join(x = trio_df, y = trio_prescreening, by = c("Sub.Num", "Tr.Num"))
```

### Add variable to track language 

```{r}
v1_df$language_modality <- "ASL"
trio_df$language_modality <- "English"
trio_df$stimuli <- "trio"
```

### Filter ASL data to just keep frames 0 - 3000

```{r}
v1_df_filtered <- v1_df %>% 
    select(Sub.Num, Months, Tr.Num, Response, RT, stimuli,
           Prescreen.Notes, language_modality, X0:X3133) %>% 
    mutate(Sub.Num = as.character(Sub.Num),
           Tr.Num = as.character(Tr.Num)) 

trio_df_filtered <- trio_df %>% 
    select(Sub.Num, Months, Tr.Num, Response, Target.RT..sec., stimuli,
           PSO.Reason, language_modality, X0:X3133) %>% 
    rename(Prescreen.Notes = PSO.Reason,
           RT = Target.RT..sec.) %>% 
    mutate(Months = as.integer(Months),
           X3133 = as.character(X3133),
           RT = as.integer(RT) * 1000)
```

### Bind data frames together

```{r}
speed_acc_df_final <- bind_rows(v1_df_filtered, trio_df_filtered)
```

### Save final/merged data frame

```{r}
write.csv(speed_acc_df_final, file = "sol-speed-acc-final-iChart.csv", row.names = F, na = "NA")
```